### ISSUE TITLE
How to make suggested changes in a review? 

### ISSUE THREAD

**Issue by kennysong** [ReviewNB/support#101]
Hi, great app. Is there a way to make a suggested change in a review? It's not clear if it's supported in the UI.

**Comment by amit1rrr** [comment]
@kennysong Glad you like the app. Unfortunately, we don't have a way to make "suggested changes" as you've on GitHub. Primarily because we don't ask for write permission to the repository so we won't be able to automatically apply/commit those suggestions.

The next best alternative is to show your changes inside a code block in the comment. That way the author can simply copy-paste it (if they so wish). Hope that helps.
