### ISSUE TITLE
Comments in reviewnb are not placed on correct line in bitbucket PR

### ISSUE THREAD

**Issue by alonme** [ReviewNB/support#113]
The comments are placed in the top of the file and not on the correct line

**Comment by amit1rrr** [comment]
@alonme thanks for opening the issue.

This is by design.  It's because -
- We accept comments at cell level & line level. Some platforms (including Bitbucket) do not accept multi-line comments so we're not able to attach cell level comments to the correct set of lines.
- Some platforms (mainly GitHub) do not accept comments on non-modified parts of the file. ReviewNB accepts comments anywhere in the notebook, so if you've a comment on a line that's not modified in the PR then we're not able to post it to corresponding line in PR.


To avoid above issues (and some others), we attach all discussions to first line of the PR (with certain metadata in the comment HTML indicating where the comment actually belongs). So if you open the comments in ReviewNB, it will always show you next to the correct cell or line.  

Hope this helps.
