### ISSUE TITLE
Link GitHub PR comments to their matching ReviewNB conversations

### ISSUE THREAD

**Issue by ojustino** [ReviewNB/support#122]
Hi, I notice that comments made on the ReviewNB page show up in the GitHub pull request with a link to that PR's general "Discussion" page at the bottom. I think it would be helpful to instead link to the matching comment itself, whether it's the version on the "Discussion" page or the one in the context of the rendered notebook. (I personally prefer the latter.)

I often work with PR authors who aren't familiar with ReviewNB, so this could save them some clicks and frustration as they get used to the service. I see that comments on one of ReviewNB's  "Discussion" or diff pages already have a button that links to their counterpart on the other, so hopefully this would be a simple addition to the comment creation process.

**Comment by amit1rrr** [comment]
Hello @ojustino, thank you for the feedback. It'd definitely be more useful to link to the specific comment anchor on the page instead of simply linking to the PR page itself. 

The tricky bit here is that we're currently using GitHub Comment IDs as anchors which are available AFTER the comment is posted to GitHub. There are a couple of ideas to work around it, we just need to prioritize & solve this.

I'm keeping this issue open & we'll hopefully resolve this in the next few weeks. It'll be a nice small win to start the new year :)

Meanwhile, keep that feedback coming. Always happy to improve the user experience any way we can.

**Comment by amit1rrr** [comment]
@ojustino This is now released. 

PR comment links should now scroll you to the specific comment on the page. Additionally, every comment now has a "Copy Link" button that you can use to copy & share the URL internally if required.

Resolving, but do let me know how this works for you. And keep that feedback coming :)

**Comment by ojustino** [comment]
Hello @amit1rrr, I just got to test this for the first time and it now works the way I'd expect. Thank you for the update.
