### ISSUE TITLE
GIthub Marketplace 404 error

### ISSUE THREAD

**Issue by ChenQuan** [ReviewNB/support#14]
https://github.com/marketplace/review-notebook-app
![image](https://user-images.githubusercontent.com/20548053/54650904-70197f80-4aeb-11e9-8598-47a4152a8a5e.png)

**Comment by amit1rrr** [comment]
Marketplace application is under review at the moment. Hence you can't see that page.

If you just want to see the application on GitHub, you can access it here: https://github.com/apps/review-notebook-app

If you were visiting that page to upgrade your plan, you don't need to do that yet because we are still in beta.
