### ISSUE TITLE
Cannot access pull request.

### ISSUE THREAD

**Issue by ChenQuan** [ReviewNB/support#15]
link:https://app.reviewnb.com/OpenSourceAI/kaggle-competition-details/pull/3/

![image](https://user-images.githubusercontent.com/20548053/54651723-1450f580-4aef-11e9-9648-46aec23cfc98.png)
I have checked my permissions and it is correct.

![image](https://user-images.githubusercontent.com/20548053/54651853-9a6d3c00-4aef-11e9-8ab9-54b0fb280367.png)

**Comment by amit1rrr** [comment]
The issue is that some of the filenames in the PR have unicode characters (mandarin I'm guessing) which are not handled well currently. 

I'll see if I can work around some of the issues I had earlier around unicode handling. I can't promise it but will give it a go and update the post here. 

Meanwhile you can try renaming the filenames to only have ascii characters (normal English) and see if that works for you.

**Comment by ChenQuan** [comment]
> The issue is that some of the filenames in the PR have unicode characters (mandarin I'm guessing) which are not handled well currently.
> 
> I'll see if I can work around some of the issues I had earlier around unicode handling. I can't promise it'll work but will give it a go and update the post here.
> 
> Meanwhile you can try renaming the filenames to only have ascii characters (normal English) and see if that works for you.

OK,I try it.

**Comment by amit1rrr** [comment]
I have fixed the unicode processing issues on git patches. You should be able to access the PR now. 

 https://app.reviewnb.com/OpenSourceAI/kaggle-competition-details/pull/3/

**Comment by ChenQuan** [comment]
Good job.Thanks.
