### ISSUE TITLE
Pending comments are not saved?

### ISSUE THREAD

**Issue by gsganden** [ReviewNB/support#25]
I made some comments but did not finish my review, and the next day those comments seemed to be gone. Is it possible to support pending comments like on GitHub, so that comments are saved across sessions even if the review is unfinished? If not, then would it be possible to change the UI to clarify that comments in unfinished reviews will not be saved?

**Comment by amit1rrr** [comment]
Storing unfinished review means we'll have to persist those comments on ReviewNB side. We do not want to store user's private repository data (including comments). 

> If not, then would it be possible to change the UI to clarify that comments in unfinished reviews will not be saved?

This is a good idea. Would some sort of a pop up if you try to close the tab with unfinished review be helpful?

**Comment by gsganden** [comment]
> Storing unfinished review means we'll have to persist those comments on ReviewNB side. We do not want to store user's private repository data (including comments).

That makes sense. Would it be possible to use GitHub's pending comments functionality to avoid this problem?

> This is a good idea. Would some sort of a pop up if you try to close the tab with unfinished review be helpful?

Yes. Maybe also use different language than "Start Review" and "Finish Review," because to me that language calls to mind GitHub's ability to store pending comments while you work on a review.

**Comment by amit1rrr** [comment]
> Would it be possible to use GitHub's pending comments functionality to avoid this problem?

It's possible but will be a bit murky since people tend to use both interfaces (ReviewNB & GitHub) to create reviews. If we keep ReviewNB draft review in GitHub pending review state they won't be 
able to 
1. create a new review draft in GitHub (since GitHub only allows 1 pending review)
2. won't be able to continue/finish the review in GitHub interface (because we add some additional metadata to comment cell_index etc.)
3. won't be able to read the draft review correctly in GitHub (because cell level comments you create in ReviewNB are not tied to a specific line as the comments created in GitHub)

For all these reasons, I'm not very inclined to piggyback on GitHub pending review. Maybe we can change this in future when users are using ReviewNB commenting exclusively & won't care if there's a draft review in GitHub UI. 

> Yes. Maybe also use different language than "Start Review" and "Finish Review," because to me that language calls to mind GitHub's ability to store pending comments while you work on a review.

Cool. I will have some kind of pop up show up to let people know that they might loose comments. 

About wording, the intention was to keep it same so people can relate easily and know that this review will be posted as is on GitHub. You're right that the mental model breaks for draft review. I will make the pop up wording explicitly clear so that people know this distinction before they loose their carefully crafted review comments.

Also, I am sorry you lost those comments you wrote!

**Comment by gsganden** [comment]
Thanks! The product is very helpful.

**Comment by amit1rrr** [comment]
@gsganden App is now updated to show pop ups when the tab is getting closed or navigated away from when there are pending comments. Screenshot below. 

Please note that some browsers (including Chrome) shows their own default confirm message in the pop up instead of our tailored message. In any case, it serves our purpose of giving user another chance to save their work.

Thank you for reporting.

![Screenshot 2019-05-07 at 5 42 53 PM](https://user-images.githubusercontent.com/1350490/57299093-61197b80-70f1-11e9-9f23-ac6088effa19.png)
