### ISSUE TITLE
Minor error in diff highlighting of a markdown cell

### ISSUE THREAD

**Issue by juhoautio** [ReviewNB/support#32]
![Näyttökuva 2019-6-19 kello 11 26 40](https://user-images.githubusercontent.com/4446608/59749133-2163b900-9285-11e9-9cc6-8b6124bdf7bf.png)

I wonder why the first bullet point is also highlighted although it didn't change.

It can be seen live here:
https://app.reviewnb.com/juhoautio/NotebookTest/pull/1/files/

**Comment by amit1rrr** [comment]
@juhoautio In this case a newline (\n) character got added to the first bullet that's why it's highlighted in green.

As you can see in the text diff here - https://github.com/juhoautio/NotebookTest/pull/1/files#diff-933ae29e83f5704b1f97d0c3ca04fb25R9

I am closing this but feel free to reopen the issue if you have any follow up questions.

**Comment by juhoautio** [comment]
The github diff is able to show a similar (non-notebook) markdown change "properly" in the rich diff:

<img width="999" alt="Näyttökuva 2019-6-21 kello 0 06 25" src="https://user-images.githubusercontent.com/4446608/59881509-79e7a300-93b8-11e9-9090-c2511be4d13c.png">

https://github.com/juhoautio/NotebookTest/commit/0f8c6dab0404b3d8d56d1b1ed9481a376a69718a?short_path=91b5c4a#diff-91b5c4a22fc6103c73bb91e4a40568f8

..even though it's not highlighting the newline-only change in any visible way in the raw diff:

<img width="994" alt="Näyttökuva 2019-6-21 kello 0 06 35" src="https://user-images.githubusercontent.com/4446608/59881521-7fdd8400-93b8-11e9-9879-29c35a9ba22b.png">

https://github.com/juhoautio/NotebookTest/commit/0f8c6dab0404b3d8d56d1b1ed9481a376a69718a#diff-91b5c4a22fc6103c73bb91e4a40568f8

I'd expect ReviewNB to display markdown cell diffs in the same way, but of course it's debatable which one is even correct. Maybe you consider this as a possible improvement for ReviewNB, maybe not? :)

----

In some cases github does something like this even in the raw diff, eg. here the changed number of `execution_count`:

<img width="557" alt="Näyttökuva 2019-6-21 kello 0 03 37" src="https://user-images.githubusercontent.com/4446608/59881366-1198c180-93b8-11e9-825e-b672d9f74c90.png">

But when the change is newline, I guess there's no similar thing (yet?).

----

To create the initial test file without an ending newline I used this:

`printf "%s" "- something" > file.md`

**Comment by amit1rrr** [comment]
@juhoautio I like your suggestion. I like to call our diff as **visual diff** and since nothing is visually different in your example there is no need to highlight the newline change.

I have gone ahead and deployed the fix. Now we don't highlight newline changes if they are non-visual like in this case. Refer to screenshot below.

P.S. - There could be some whitespace changes that are harder to detect whether they make visual difference or not (e.g. HTML outputs) so we aren't handling those yet but this is a good start.

Thanks for following up.

![Screenshot 2019-06-21 at 12 40 55 PM](https://user-images.githubusercontent.com/1350490/59904717-e5b22600-9421-11e9-93a6-722240bcd77a.png)
