### ISSUE TITLE
comment form missing from many cells

### ISSUE THREAD

**Issue by lukeorland** [ReviewNB/support#35]
Many changed lines inside cells are shown in the side-by-side notebook diff, but only a few of the many cells have a blue "+" icon that allows opening a comment box for that cell.

**Comment by amit1rrr** [comment]
Thanks for reporting the issue @lukeorland 

After looking at the PR you linked in email, it turned out there is a bug on our side which wouldn't render the comment form for some cells when there are lot of structural changes to the notebook (cells getting added, deleted, merged).

I am building a fix for this at the moment, expect it to be released in a day or two.

**Comment by amit1rrr** [comment]
@lukeorland Fix is now deployed. You should be able to comment on all the cells in any PR. If you see this or any other issue again, feel free to reopen. Thanks again!
