### ISSUE TITLE
[Feature Request] Summary Review Comment

### ISSUE THREAD

**Issue by alanhdu** [ReviewNB/support#39]
In Github's code review interface, you are able to leave line-by-line comments, along with a general comment summarizing the overall review. I'd love to be able to have that "overall comment" feature for ReviewNB too! Right now, all comments (I think?) have to be attached to different parts of the notebook, but sometimes I want to give some overall suggestions/comments on the organization or logic of the notebook.

**Comment by amit1rrr** [comment]
@alanhdu - we do have issue comments that are meant to discuss overall changes. You can write these comments directly from the 'Discussion' tab in the PR.

Let me know if this is something you were looking for.

**Comment by alanhdu** [comment]
@amit1rrr There's the overall discussion page, but those aren't "bundled" into the same review as the cell-by-cell comments. In Github, there is:

![image](https://user-images.githubusercontent.com/1914111/63353870-682b6900-c331-11e9-9d04-d28d17371aa1.png)

which lets you submit a summary comment over the entire commit. This has two nice properties:
- From a UI perspective, you don't need to switch tabs when composing the overall comment
- From a Github perspective, the PR author only receives 1 notification (for the entire review) instead of 2 (one for the cell-by-cell review, one for the unattached comment)

**Comment by amit1rrr** [comment]
Yep, I'm aware of the overall comment that's attached to the review itself. I intentionally left it out of ReviewNB because it felt like the need for overall PR comment is well served by Issue Comments under the Discussion tab. The downside of tying it to every review in the UI is, somehow it feel like writing an overall message is required/encouraged. 

But maybe I'm wrong, so let's keep this feature request open for some more votes. If multiple people find it useful, I'm open to adding this feature.

**All Readers - If you find it useful to write overall review message with your reviews. Please upvote @alanhdu's comment above.**

**Comment by amit1rrr** [comment]
Closing. This is now moved to #78
