### ISSUE TITLE
Some diffs are showing up as "Everything changed"

### ISSUE THREAD

**Issue by MarkDaoust** [ReviewNB/support#43]
In the two PR's below I made "obviously"-diffable changes but ReviewNB's diff viewer just says "everyhting changed":

All the notebooks in this PR:

https://github.com/tensorflow/addons/pull/578
https://app.reviewnb.com/tensorflow/addons/pull/578/

The "image_ops.ipynb" notebok in this one:
https://github.com/tensorflow/addons/pull/583
https://app.reviewnb.com/tensorflow/addons/pull/583/files/

I'm not sure if it depends on how I saved the notebook, or, if I cleared the output or what. 
It just feels like all of these should line up better.

WDYT?

**Comment by amit1rrr** [comment]
@MarkDaoust thanks for reporting the issue. 

Our diff algorithm is based on the git diff that is created by git. As you can see in the examples you posted that the diff on GitHub treats the entire file as changed. This happens when the file is changed significantly. Hence you see the ReviewNB diff also to be everything changed. Which seems like the right thing to show in these cases. 

Being said that there could be some examples where we should show side by side diffs but are not. I'd like to learn about such examples and see if we can fix them.

**Comment by MarkDaoust** [comment]
Hi Amit, thanks for the response.

> git diff that is created by git.

"git diff" does say everything changed. 

I think the problem here is mostly  whitespace.
Using "git diff -w" gives much better alignment:

```
    "source": [
-        "mean = tfa.image.mean_filter2d(google_img, filter_shape=5)\n",
+    "mean = tfa.image.mean_filter2d(img, filter_shape=11)\n",
     "_ = plt.imshow(mean)"
     ],
```
An ideal solution would be to separate the data-structure from it's representation: Only diff the cell source and output fields. 

But if you could rig this up to use `-w` I bet it would be a clear improvement for these cases.

**Comment by amit1rrr** [comment]
Sorry for the delay.

> An ideal solution would be to separate the data-structure from it's representation: Only diff the cell source and output fields.

For actual diffs at cell level we only consider changes in JSON strings under source/output sections. At notebook level,  it's tricky to only diff source/outputs when notebook cells have been merged/split/deleted (it's non-trivial to determine which pre-cell to compare with which post-cell/s). Hence we use git diff as a base/anchor at notebook level and then at each cell apply our diffing algorithm which discounts non source/output changes.

> if you could rig this up to use -w I bet it would be a clear improvement for these cases.

Looking at the -w documentation it ignores ALL whitespaces. So it'd ignore whitespace changes in source/outputs as well. Do you have some ideas here? For the examples you gave, was "everything changed" in git diff mainly due to whitespace changes in JSON? What causes JSON whitespace changes in Jupyter context? Are you using Google Colab & Jupyter interchangeably?

Just asking these questions to understand the problem better.

**Comment by MarkDaoust** [comment]
> merged/split/deleted

Yeah... I guess one option here would be running through `jupyter nbconvert --to markdown` and diffing the markdown,  or something like that. or some sort of json normalization first. (?).

> Are you using Google Colab & Jupyter interchangeably?

This is probably caused mainly by that. We could be stricter about making all PR's use one or the other. But it does seem like this could be a common problem for other opensoure projects.

Thanks again Amit.

**Comment by amit1rrr** [comment]
> or some sort of json normalization first. (?).

The solution for this would be to not rely on git diff but look at pre and post notebook cells list and compute the diff from scratch. I.e. Determine whether each pre cell was deleted/merged/split/unchanged and so on. In that approach the JSON structure would have no impact on the final diff result.

But this approach has a different problem - it becomes heuristics based on string similarity. These are often impossible to get right 100% of the time ("were 2 cells merged and 3rd got changed OR all 3 merged"). So it's a bit of a wise decision to start off of git diff which has more refined algorithm for detecting changes to parts of the file.

Finally, the effort to change something that fundamental in ReviewNB is large and the problem is not that widespread (from what I have seen).  

> We could be stricter about making all PR's use one or the other.

You could give users freedom to use Jupyter & Colab interchangeably but at the end make a cleanup commit before publishing a PR. That cleanup commit could also be automated based off of a new PR created webhook.

**Comment by MarkDaoust** [comment]
Cool, thanks for taking the time to discuss. 

> That cleanup commit could also be automated based off of a new PR created webhook.

That is a possibility.

Thanks!
