### ISSUE TITLE
markdown is incorrectly displayed

### ISSUE THREAD

**Issue by pete88b** [ReviewNB/support#63]
https://app.reviewnb.com/fastai/nbdev/pull/184/files/ nbs/00_export.ipynb shows a section of markdown as:

![image](https://user-images.githubusercontent.com/11458288/86755175-57fba580-c039-11ea-99df-fe86c070781a.png)

this same section is shown via github as:
![image](https://user-images.githubusercontent.com/11458288/86755859-dbb59200-c039-11ea-9006-eab3d95dd65a.png)

**Comment by amit1rrr** [comment]
@pete88b Thank you for reporting the issue. Turned out we were mixing up markdown code block comments (starting with #)  with markdown headers (also starting with #). We've deployed a fix that fixes the issue. See screenshot below.

Closing. Feel free to reopen if you see any problems.

![Screenshot 2020-07-08 at 2 04 00 PM](https://user-images.githubusercontent.com/1350490/86896663-ee0bfa80-c123-11ea-9573-48ac08ce4d2d.png)
