### ISSUE TITLE
[Bug] `review-notebook-app` GH bot comments on every commit

### ISSUE THREAD

**Issue by alanhdu** [ReviewNB/support#65]
Hi!

It seems that sometime in the last couple of days (maybe last week), the `review-notebook-app` Github bot has started leaving comments on *every* commit in a PR to edit a notebook (notice the "commented on 2ff8abe"):

![image](https://user-images.githubusercontent.com/1914111/89545382-45f45a80-d7d1-11ea-92b1-82bec12cbb13.png)

IMO, this was an unfortunate change, leading to lots of duplicate comments and unnecessary notifications. Would it be possible to revert whatever change caused this?

Thanks!

**Comment by amit1rrr** [comment]
@alanhdu Yes, we introduced a new feature this week which puts a comment on a GitHub commit if the commit contains notebook changes.

> IMO, this was an unfortunate change, leading to lots of duplicate comments and unnecessary notifications. Would it be possible to revert whatever change caused this?

Sure, let me know the name of your repositories and we can disabled commit notifications for you.

I'd really appreciate some more information to see if we can make this more useful feature for everyone -

- The central idea here is having a ReviewNB link available on the commit itself.  So anyone looking at the commit can see what changed in the notebook. In your workflow, is that link useful on the commit?

- Is the main annoyance due to number of notifications? E.g. 8 commits pushed would post 8 messages which would generate 8 notifications from GitHub. 

- Just now we deployed a change to disable these comments on commits generated by a bot (e.g. `github-actions[bot]`). These are usually automated workflows and no need to review those explicitly. We also disabled these commits on `gh-pages` branch since it is used for GitHub pages deployment. Can some more (smarter) rules in this regard help only keep useful notifications?

**Comment by alanhdu** [comment]
Thanks for the quick response! Our repository is `ctrl-labs/notebooks` (it's a private repo).

I would say that the main annoyance is the # of notifications. In our use-case, we use notebooks to write-up scientific results of experiments, and use ReviewNB to do a scientific reviews of the contents. That means *every* commit of the PR edits the notebook-in-review. We're all already using ReviewNB for review, so repeated comments are just distractions (and unnecessary notifications).

In our workflow, it's not that useful to have the links embedded with the commit, because we associate the review with the PR instead. Maybe a simple heuristic, like "only comment on commits if you haven't commented on the PR" or "comment on a PR at most once" would work?

**Comment by amit1rrr** [comment]
Thank you for explaining your workflow. 

> In our workflow, it's not that useful to have the links embedded with the commit, because we associate the review with the PR instead.

Makes sense. Since you review all changes at the PR level, I've gone ahead and disabled commit comments for the repository you mentioned. Let me know if that doesn't work for some reason.


> I would say that the main annoyance is the # of notifications.

Thanks for letting us know. We've made some changes to reduce these notifications for everyone (e.g. if there's a batch of commits pushed only post one comment/notification). We'd also like to be a bit smarter in the future (e.g. skip commit comment if there's an active PR for this branch), it's a bit tricky but we'll get there!
