### ISSUE TITLE
Comment emails being routed to incorrect email address

### ISSUE THREAD

**Issue by setu4993** [ReviewNB/support#67]
I have 2 email addresses associated with my GitHub account (one personal, one for an organization). All notification emails for my organization are routed to a the org email (via GitHub Settings).

However, ReviewNB sends comment emails to my personal email instead of the org email, even though the PR ReviewNB is referring to is on an org repo (and comments made on the PR on GitHub go to the org email).

**Comment by amit1rrr** [comment]
There are 2 types of email notifications from ReviewNB

- PR Comments: These comments are directly posted to pull request on GitHub and hence the notifications are managed by GitHub (this will honour your org email settings)

- Direct Notebook Comments ([JDoc](https://blog.reviewnb.com/commenting-for-jupyter/)): These are sent by our email server (since there's no way to post file comments on GitHub). We only store your primary email address on GitHub and don't have access to other org level settings. Hence these emails go to your primary email address on GitHub. Anyone can request us to change their primary email address (by writing to `support@reviewnb.com`) or they could do so directly on GitHub and then logout-login into ReviewNB.

In this case, we've updated your email address to the work email and all future notifications should come on that address. Please note, if there's a JDoc comment notification on one of your non work repository, the notification will still be sent to the primary email we have on file (i.e. your work email now). I understand that this is sub-optimal but we don't have access to user's GitHub settings at the moment.

**Comment by amit1rrr** [comment]
Sorry, just read this more closely.

> even though the PR ReviewNB is referring to is on an org repo

Can you please confirm whether this is a PR comment or a JDoc Comment (comment that's directly on the notebook file)? Also, is the email coming from us (notifications@reviewnb.com) or from GitHub (notifications@github.com)?

**Comment by setu4993** [comment]
Thanks @amit1rrr, that makes a lot of sense. This was for JDoc comments, received from `notifications@reviewnb.com`. I understand that it is not possible to get access to org-level notification routing, so knowing that there's a workaround (even if it is not automatic) works.

To summarize: JDoc comments go to the primary email on the account, unless specifically requested to be changed, which can be done by emailing `support@reviewnb.com`.

**Comment by amit1rrr** [comment]
Small update -

We've made our JDoc notification system a bit more smart. Now if a JDoc comment is made on a repo in XYZ org AND if User has `xyz.com` domain email then we prefer that email to send that particular notification (even though it might not be the primary email on the User's account). 

P.S. Actual domain to org name matching is a bit more nuanced but ultimately achieves the above effect.

P.S. Existing Users need to logout & login for the effect to take place.

**Comment by setu4993** [comment]
Good change, thanks for keeping this updated!
