### ISSUE TITLE
Provide an option to make reviews of public notebooks public

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ReviewNB/support#75]
This is especially important since it currently does not seem to be possible to use ReviewNB to review notebooks in repos owned by someone else.

**Comment by amit1rrr** [comment]
Are you asking to make reviews public in that they should be available to view without any login? Or are you requesting a feature where one should be able to review any public repository?

**Comment by Daniel-Mietchen** [comment]
@amit1rrr I would like both of these options, but this ticket was specifically about the former, since the latter can be approximated by forking the repo to be reviewed, and running ReviewNB on that (just as I did in my test).

**Comment by amit1rrr** [comment]
Showing public reviews/commits/PRs is not possible due to GitHub API limitations. When we make calls to GitHub to fetch this content we make the call on behalf of the logged in user (with user's access token). Without this token we'd quickly run into GitHub's API [rate limits](https://developer.github.com/v3/#rate-limiting) and won't be able to fetch the content.
