### ISSUE TITLE
ReviewNB shows entire notebook has having changed, rather than showing cell-by-cell comparisons

### ISSUE THREAD

**Issue by MarcoGorelli** [ReviewNB/support#76]
Here's the PR - https://github.com/pymc-devs/pymc3/pull/4215

Rather than showing something like

![image](https://user-images.githubusercontent.com/33491632/99185200-43928c80-2740-11eb-8e89-b14e9e19a61a.png)

it is instead showing

![image](https://user-images.githubusercontent.com/33491632/99185243-73da2b00-2740-11eb-8f21-85b66f418d1a.png)

and

![image](https://user-images.githubusercontent.com/33491632/99185250-7c326600-2740-11eb-9259-d2703cdf0f1c.png)

Any ideas why?

----

For the second pair of screenshots, I ran the notebook on Kaggle - does any  of the metadata they add make it look like all the cells are completely different?

**Comment by MarcoGorelli** [comment]
Seems that removing `papermill` from the metadata does the trick

**Comment by amit1rrr** [comment]
Thanks for reporting. Looks like metadata created by papermill is not being handled well. We're going to dig some deeper and see if we can fix this behaviour.

**Comment by MarcoGorelli** [comment]
Cool, thanks! To be clear, I just needed to remove `papermill` from the notebook's metadata, not from each cell's metadata

**Comment by cfoisy-osisoft** [comment]
We face the same problem but we have no papermill metadata, only long outputs which may throw a wrench in the diff. Do hiding cell outputs within ReviewNB performs a new diff without considering them? (I suspect not). Our PR at https://app.reviewnb.com/cfoisy-osisoft/OSI-Samples-OCS/pull/5/files/

**Comment by amit1rrr** [comment]
@MarcoGorelli We've deployed a fix to handle notebook level metadata more carefully. You shouldn't see any issues due to papermill metadata going forward. The fix can be seen on this commit: https://app.reviewnb.com/pymc-devs/pymc3/commit/cf435e1560f81c5e3d61d0666c3bbd7fbe12290b/


@cfoisy-osisoft If there are a lot of cell level changes (cells being split, merged, deleted, added) in a given PR/commit then our algorithm might not be able to compute line by line diff. In such cases we resort to [simple diff](https://github.com/ReviewNB/support/issues/21) which is what has happened in your case. 


> Do hiding cell outputs within ReviewNB performs a new diff without considering them? (I suspect not). 

No. "Hide Output" is just a UI switch to hide outputs, it doesn't recompute the diff.
