### ISSUE TITLE
Custom Routing setting not respected (Discussion notification emails going to a different address from GitHub settings)

### ISSUE THREAD

**Issue by coopr** [ReviewNB/support#90]
I have a few email addresses associated with my GitHub account, and a few orgs.

Org XYZ is set to receive email notifications at email 123 in "Custom Routing" at the bottom of https://github.com/settings/notifications

Recently, ReviewNB (or maybe GitHub) has started sending notifications to email 456. 

How can I have ReviewNB send notifications to the 123 email address, as configured in Custom Routing, rather than to the 456 email address?

**Comment by amit1rrr** [comment]
Hello @coopr, 
The issue here is we (ReviewNB) do not yet have visibility into "custom routing" i.e. these notification settings are not accessible via GitHub API yet. So we basically send all our notifications to a primary email associated with your GitHub account. 

We can update your email address in our system so that all future notifications would go to an email address you like. But we don't yet have a way to configure separate email addresses per org. (we're hoping that GitHub would soon open up an API for us to read "Custom routing" settings and we'll just honour that but sorry GitHub is not there yet).

If you'd like to update your email address in ReviewNB please [update your primary email on GitHub](https://github.com/settings/emails) and simply logout & login again to ReviewNB. All future notifications would go to your newly updated primary email address.

**Comment by amit1rrr** [comment]
Closing. Feel free to reopen if there's anything else we can do here.

P.S. - We've opened a request with GitHub for API access to Customer Routing.

**Comment by amit1rrr** [comment]
Small update -

We've made our JDoc notification system a bit more smart. Now if a JDoc comment is made on a repo in XYZ org AND if User has `xyz.com` domain email then we prefer that email to send that particular notification (even though it might not be the primary email on the User's account). 

P.S. Actual domain to org name matching is a bit more nuanced but ultimately achieves the above effect.

P.S. Existing Users need to logout & login for the effect to take place.
