### ISSUE TITLE
Comments are out of order 

### ISSUE THREAD

**Issue by BasilPH** [ReviewNB/support#92]
We're discussing a PR on ReviewNB, but our comments appear of order. See the timestamps of the comments in the image below:
![reviewnb_ordering](https://user-images.githubusercontent.com/1204545/120689258-f2df4880-c471-11eb-93ac-35ddd1288b69.png)

**Comment by amit1rrr** [comment]
@BasilPH Thank you for opening an issue and sharing the screenshot. There was indeed a problem with ordering of replies on some of the Conversations. We've deployed a fix that should show everything in the correct order. 

Closing. Thanks again, do let us know if your issue is resolved & feel free to reopen if there's any problem.
