### ISSUE TITLE
can you support commenting when commit like when pull request??

### ISSUE THREAD

**Issue by planetb113** [ReviewNB/support#93]

**Comment by amit1rrr** [comment]
Sorry we're unable to understand the issue. Can you please describe the problem a little more?

**Comment by planetb113** [comment]
> Sorry we're unable to understand the issue. Can you please describe the problem a little more?
![截屏2021-06-20 下午2 25 44](https://user-images.githubusercontent.com/33831002/122664459-17f2eb80-d1d4-11eb-9f52-732f3ab2b2ff.png)
![截屏2021-06-20 下午2 23 59](https://user-images.githubusercontent.com/33831002/122664465-1cb79f80-d1d4-11eb-8db7-8a246edc64b5.png)

I mean reviewnb support rich diffs and commenting when review a pull request, but only support rich diffs in commit, can you support commenting when commit like when pull request?

@amit1rrr

**Comment by amit1rrr** [comment]
Thanks for the explanation. 

By design, we only allow 2 type of comments - 

1. Pull Request Comments - Typical software development workflow wherein a set of changes are reviewed until they're approved for merge.
2. JDoc comments - GoogleDoc style comments on notebook itself. These are good for a quick comment or discussion with non-technical stakeholders who typically don't care about the diff view.

We believe these 2 types of notebook comments cover all the collaboration requirements of data science teams. Please let me know if there's any workflow that doesn't fit either of these.

Now here's the main issue with Commit level comments - 

- Lack of container for continued discussion. E.g. Say an author receives some feedback on their work and they make some changes in response to that feedback. Now the new work is in a separate commit. What if reviewers have some more feedback on the updated files? They need to open a new discussion on the new commit. That way a single discussion is spread over multiple commits and it's hard to track all open discussions. Pull Request solves this exact problem.
