### ISSUE TITLE
Databricks connection with github

### ISSUE THREAD

**Issue by anguitart** [ReviewNB/support#95]
Notebooks uploaded connecting github from Databricks, are not correctly shown by ReviewNB.
They are always shown as new notebooks instead of showing just the changes made in the same notebook.

Summary: Issue relies in that the modifications in .ipynb notebook coming from Databricks are not correctly found.
Do you have any solution for this?

**Comment by amit1rrr** [comment]
Most likely the issue is that Databricks formats the notebook as an entire JSON blob on a single line. I.e. unlike standard Jupyter editor, there are no newline characters present in the notebook created / edited by Databricks. As a result, git cannot detect changes made in the notebook file. Git patch simply says that this single long line was edited. Our diff'ing algorithm is based on git diff / patch and because those are not generated properly with Databricks, ReviewNB does not work well with those notebooks.

There's no easy workaround for us in this situation. Maybe asking Databricks to store their notebooks in standard Jupyter format might help.

**Comment by amit1rrr** [comment]
(if the above explanation does not sound correct for some reason, please share demo commit or PR on GitHub with notebooks created from Databricks & we'll take a deeper look)

**Comment by anguitart** [comment]
Thank you! It was very helpful. I will try to do that and open this issue for their side.
