### ISSUE TITLE
Comments tied to a Standalone notebook are invisible and easily lost

### ISSUE THREAD

**Issue by tobiszuts-at-affirm** [ReviewNB/support#97]
**Problem**
It's possible to add comments to a notebook that's viewed in 'Standalone' mode.  However, doing so has two bugs:
1) the owner of the PR is not automatically notified of these comments (they would need to go to the same notebook in Standalone mode and toggle the switch to subscribe to comments).
2) New commits cause the comments (which are tied to the old standalone notebook) to be lost, since old commits no longer have associated Standalone notebooks: this is the far more serious problem.

**Potential solution**
The ideal behavior, from my perspective, would be to log those comments in the main discussion page of the PR (just like when commenting in a notebook not in Standalone mode), send out emails, and retain them even with new commits.

**Comment by amit1rrr** [comment]
@tobiszuts-at-affirm Thanks for reporting. 

There are 2 types of comments in ReviewNB-
- PR Comments: These are posted on a pull request diff.
- JDoc Comments: These are posted on a standalone notebook file.

These are two **separate** functionalities built for slightly different use cases that you can read more about [here](https://blog.reviewnb.com/commenting-for-jupyter/). The crux of the issue is, the standalone notebook (and any comments on it) are not tied to any pull request as such. Standalone notebooks are more like a GoogleDoc for Jupyter Notebooks.

I can understand that some of the confusion is arising because we link to standalone notebook from the PR diff page. So it feels like they're connected to the PR (but they're not).

> the owner of the PR is not automatically notified of these comments (they would need to go to the same notebook in Standalone mode and toggle the switch to subscribe to comments).

Everybody "watching" the repository on GitHub are automatically notified of comments on any standalone notebook in the repo. So anyone who's interested in receiving updates should just mark themselves as "watching" the repository on GitHub. As I explained above, standalone notebooks are not tied to any PR so we don't automatically subscribe the PR author to these notifications.

> New commits cause the comments (which are tied to the old standalone notebook) to be lost, since old commits no longer have associated Standalone notebooks

All comments on a standalone notebook should be visible on the same standalone notebook (even if the comments are made at different commits). The only way you could _loose comments_ is if subsequent commit renamed the notebook. If this is happening outside of that, do let us know & we'll look into it.

**Comment by tobiszuts-at-affirm** [comment]
Hi Amit,

Thank you kindly for the great explanation - I was making a lot of
assumptions about how things are worked, and it's now clear to me how these
different use cases interact.  (I didn't know about the standalone notebook
features, and I'll start using them more!)

The commit in question moved the notebook to a new directory although the
name remains the same, so it's probably that known use case you mention.

Still, it would be a nice feature not to lose any comments when moving a
notebook around: I regularly refactor like this as a project develops, and
it's unfortunate that such a simple action can cause comments to be deleted
forever.

Thanks again for the quick response!
Tobi

**Comment by amit1rrr** [comment]
> Still, it would be a nice feature not to lose any comments when moving a notebook around: I regularly refactor like this as a project develops, and it's unfortunate that such a simple action can cause comments to be deleted forever.

I agree 100%. I've [opened an issue](https://github.com/ReviewNB/support/issues/98) to track this. 

By the way, **these comments are not really deleted, they're still available, just that they're tied to OLD file name + path**.  E.g. if you move the file to it's old path+name you will see all the comments again. Of course, this is not ideal at all. I'm just suggesting you a workaround for now to recover any important conversations that you might have _lost_ as part of moving files around.

If the above workaround is not good enough, feel free to write to me at amit@reviewnb.com with old & new file paths & we would help you with manual migration of conversations.

**Comment by tobiszuts-at-affirm** [comment]
Hi Amit,

Good to know about how to access old comments.  I read through them once
and have actually merged that PR, so now need to migrate them, although
thank you very much for the offer!  I'm also making sure my team is
commenting in the right place now. :)

Tobi
